# utf-8
from django.urls import path
from app_doc import views, util_upload_img

urlpatterns = [
    path('', views.project_list, name='pro_list'),
    path('project-<int:pro_id>/', views.project_index, name='pro_index'),
    path('create_project/', views.create_project, name='create_project'),
    path('get_pro_doc/', views.get_pro_doc, name="get_pro_doc"),
    path('get_pro_doc_tree/', views.get_pro_doc_tree, name="get_pro_doc_tree"),
    path('modify_pro/', views.modify_project, name='modify_project'),
    path('manage_project', views.manage_project, name="manage_project"),
    path('del_project/', views.del_project, name='del_project'),
    path('report_project_md/', views.report_md, name='report_md'),
    path('genera_project_file/', views.genera_project_file, name='genera_project_file'),
    path('report_project_file/', views.report_file, name='report_file'),
    path('modify_pro_role/<int:pro_id>/', views.modify_project_role, name="modify_pro_role"),
    path('modify_pro_download/<int:pro_id>/', views.modify_project_download,
         name="modify_pro_download"),
    path('check_viewcode/', views.check_viewcode, name='check_viewcode'),
    path('manage_project_colla/<int:pro_id>/', views.manage_project_collaborator,
         name="manage_pro_colla"),
    path('manage_pro_colla_self/', views.manage_pro_colla_self, name="manage_pro_colla_self"),
    path('project-<int:pro_id>/doc-<int:doc_id>/', views.doc, name='doc'),
    path('create_doc/', views.create_doc, name="create_doc"),
    path('modify_doc/<int:doc_id>/', views.modify_doc, name="modify_doc"),
    path('del_doc/', views.del_doc, name="del_doc"),
    path('manage_doc/', views.manage_doc, name="manage_doc"),
    path('diff_doc/<int:doc_id>-<int:his_id>/', views.diff_doc, name='diff_doc'),
    path('manage_doc_history/<int:doc_id>/', views.manage_doc_history,
         name='manage_doc_history'),
    path('manage_doctemp/', views.manage_doctemp, name='manage_doctemp'),
    path('create_doctemp/', views.create_doctemp, name="create_doctemp"),
    path('get_doctemp/', views.get_doctemp, name='get_doctemp'),
    path('del_doctemp/', views.del_doctemp, name="del_doctemp"),
    path('modify_doctemp/<int:doctemp_id>/', views.modify_doctemp, name="modify_doctemp"),
    path('manage_image/', views.manage_image, name="manage_image"),
    path('manage_image_group/', views.manage_img_group, name="manage_img_group"),
    path('manage_attachment/', views.manage_attachment, name='manage_attachment'),
    path('upload_doc_img/', util_upload_img.upload_img, name="upload_doc_img"),
]
